export const nextBatch = [
  { id: 1, month: "DEC", date: "23", course: "Advanced digital marketing" },
  { id: 2, month: "DEC", date: "23", course: "Basic digital marketing" },
  { id: 3, month: "DEC", date: "23", course: "Basic MERN STACK Development" },
  {
    id: 4,
    month: "DEC",
    date: "23",
    course: "Advanced MERN STACK Development",
  },
  {
    id: 5,
    month: "DEC",
    date: "23",
    course: "Basic Python-Django Development",
  },
  {
    id: 6,
    month: "DEC",
    date: "23",
    course: "Advanced Python-Django Development",
  },
  { id: 7, month: "DEC", date: "23", course: "Basic Data Science" },
  {
    id: 8,
    month: "DEC",
    date: "23",
    course: "Advanced Flutter APP Development",
  },
  { id: 9, month: "DEC", date: "23", course: "Basic Flutter APP Development" },
  { id: 10, month: "DEC", date: "23", course: "Advanced Data Science" },
  { id: 11, month: "DEC", date: "23", course: "Basic WordPress Development" },
  {
    id: 12,
    month: "DEC",
    date: "23",
    course: "Advanced WordPress Development",
  },
  { id: 13, month: "DEC", date: "23", course: "Graphic Design" },
  { id: 14, month: "DEC", date: "23", course: "UI/UX Design" },
  { id: 15, month: "DEC", date: "23", course: "Production & Post production" },
  { id: 16, month: "DEC", date: "23", course: "VFX Advanced" },
  { id: 17, month: "DEC", date: "23", course: "VFX Basic" },
];
